@baseUrl = http://localhost:8080

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome" : "radames p",
  "dataNascimento": "1991-11-21",
  "sexo": "M",
  "telefone": "49917588937",
  "celular": "499829000319",
  "email" : "radames@gmail",
  "observacao": "aluno iniciante",
  "endereco": "rua casemiro de abreu",
  "numero": "403",
  "complemento": "casa de pedra",
  "bairro": "efapi",
  "cidade": "florianopolis",
  "estado": "sc",
  "cep": "89132901"
}

### Listar alunos
GET {{baseUrl}}/alunos

### Listar alunos com paginação
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar aluno por id
GET {{baseUrl}}/alunos/1

### Atualizar aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
      "nome" : "joão jose atualizado",
      "dataNascimento": "1998-11-21",
      "sexo": "M",
      "telefone": "49917589037",
      "celular": "49982300319",
      "email" : "joao@email.com",
      "observacao": "aluno iniciante",
      "endereco": "rua casemiro de abreu",
      "numero": "404",
      "complemento": "Edificio rosa",
      "bairro": "bela vista",
      "cidade": "chapecó",
      "estado": "sc",
      "cep": "89012901"
}

### Excluir aluno
DELETE {{baseUrl}}/alunos/1

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome" : "maria heloisa",
  "dataNascimento": "1991-10-09",
  "sexo": "M",
  "telefone": "49917589037",
  "celular": "49982300319",
  "email" : "joao@email.com",
  "observacao": "aluno iniciante",
  "endereco": "rua casemiro de abreu",
  "numero": "404",
  "complemento": "Edificio rosa",
  "bairro": "bela vista",
  "cidade": "chapecó",
  "estado": "sc",
  "cep": "89012901"
}

### Cadastrar aluno inválido
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome" : "",
  "dataNascimento": "1991-10-09",
  "sexo": "Masculino",
  "telefone": "",
  "celular": "",
  "email" : "emailinvalido",
  "estado": "sampa"
}

### Listar todos
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Listar por nome
GET {{baseUrl}}/alunos?nome=joao&page=0&size=10&sort=nome,asc

### Listar por cidade
GET {{baseUrl}}/alunos?cidade=florianopolis&page=0&size=10&sort=nome,asc

### Listar por estado
GET {{baseUrl}}/alunos?estado=sc&page=0&size=10&sort=nome,asc

### Listar por email
GET {{baseUrl}}/alunos?email=joao@email.com&page=0&size=10&sort=nome,asc